/**
 * Created by Ilonze on 16/05/15.
 */

var Invoice = require('mongoose').model('Invoice');

addInvoice = function(element, index) {
    console.log('a[' + index + '] = ' + element);
    var invoice = new Invoice(element);
    invoice.save(function(err){
        if (err) {
            console.log('Error creating invoice:' + err)}
    });
}

exports.generate = function(req,res,next){

    console.log('Invoice generate called!');
    var invoices =  [
        {
            "paymentDate":new Date("20 May 2015"),
            "description":"Deloitte Touche Tohmatsu Limited, commonly referred to as Deloitte, is one of the " + "Big Four professional services firms along with PwC, EY, and KPMG." +
                            "Its global headquarters are located in the United States.Deloitte is the largest professional services network in the world by revenue and by the number of professionals." +
            " Deloitte provides audit, tax, consulting, enterprise risk and financial advisory services with more than 200,000 professionals in over 150 countries.[5] In FY 2013–14, "+
            "it earned a record $34.2 billion USD in revenues.In 2012, Accountancy Age reported that, in the UK, Deloitte had the largest number of clients amongst FTSE 250 companies.",
            "numberOfInvestors": 18,
            "percentageFunded": 76,
            "daysLeftOnFunding": 60,
            "companyName": "Deloitte",
            "companyCode": "deloite",
            "amountRemaining": 32,
            "paybackPeriod": 60,
            "annualAPR": 1.5,
            "targetAmount":2111,
            "rating":4.6

        },
        {
            "paymentDate":new Date("20 May 2015"),
            "description":"Ernst & Young Global Limited (known as EY) is a multinational professional services firm headquartered in London, United Kingdom. It is one of the " +
                        "Big Four audit firms and is the third largest professional services firm in the world by aggregated revenue in 2014.The organization operates as a network of member " +
                        " firms which are separate legal entities in individual countries. It has 190,000 employees in over 700 offices around 150 countries in the world. It provides assurance (including financial audit),"+
                        " tax, consulting and advisory services to companies.",
            "numberOfInvestors": 22,
            "percentageFunded": 30,
            "daysLeftOnFunding": 60,
            "companyName": "Ernst and Young",
            "companyCode": "ey",
            "amountRemaining": 28000,
            "paybackPeriod": 60,
            "annualAPR": 1.5,
            "targetAmount":40000,
            "rating":4.4
        },
        {
            "paymentDate":new Date("20 May 2015"),
            "description":"KPMG is one of the largest professional services companies in the world and one of the Big Four auditors, along with Deloitte, EY and PwC. Its global headquarters are located in Amsterdam, the Netherlands." +
                            "KPMG employs 162,000 people and has three lines of services: audit, tax, and advisory. Its tax and advisory services are further divided into various service groups." +
                            "The name KPMG was chosen when KMG (Klynveld Main Goerdeler) merged with Peat Marwick.",
            "numberOfInvestors": 12,
            "percentageFunded": 70,
            "daysLeftOnFunding": 28,
            "companyName": "KPMG",
            "companyCode": "kpmg",
            "amountRemaining": 30000,
            "paybackPeriod": 50,
            "annualAPR": 1.23,
            "targetAmount":100000

        },
        {
            "paymentDate":new Date("20 May 2015"),
            "description":"PricewaterhouseCoopers (trading as PwC) is a multinational professional services network. It is the world's second largest professional services network, as measured by 2014 revenues, and is one of the Big Four auditors, along with Deloitte, EY and KPMG." +
                            "PwC is a network of firms in 157 countries with more than 195,400 people. It had total revenues of $34.0 billion in FY 2014, of which $15.1 billion was generated by its Assurance practice, $8.8 billion by its Tax practice and $10.0 billion by its Advisory practice."+
                            "The firm was formed in 1998 by a merger between Coopers & Lybrand and Price Waterhouse. The trading name was shortened to PwC in September 2010 as part of a rebranding." +
                            "As of 2014 PwC United States is the 5th-largest privately owned organization in the United States.",
            "numberOfInvestors": 22,
            "percentageFunded": 50,
            "daysLeftOnFunding": 67,
            "companyName": "PWC",
            "companyCode": "pwc",
            "amountRemaining": 3000,
            "paybackPeriod": 60,
            "annualAPR": 1.12,
            "targetAmount":6000

        }


    ];
    invoices.forEach(addInvoice);
    res.redirect('/invoices');
};
exports.socketHandlers = function(io, socket){
    socket.on('getAllInvoices', function() {
        console.log('getAllInvoices');
        Invoice.getAll(function(err, invoices){
            var data = null;
            if(err){
                data = [];
            }
            else{
                io.emit('AllInvoices', {
                    invoices: invoices
                });
            }

        })
    });

    socket.on('getInvoice', function() {
        console.log('getInvoice');
        Invoice.get(function(err, invoice){
            var data = null;
            if(err){
                data = [];
            }
            else{
                io.emit('Invoice', {
                    invoice: invoice
                });
            }

        })
    });
}

exports.create = function(req, res, next) {
    console.log('invoice create function called');
    var invoice = req.body;
    new Invoice(invoice).save();
};


exports.list = function(req, res, next){
    console.log('Invoice list function called');
    Invoice.find({}, function(err, invoice){
        if(err){
            console.log('Error fetching list of invoice. Error: ' + err);
            return next(err);
        }else{
            console.log('Invoice list fetched');
            res.json(invoice);
        }
    });
};
